### ISSUE TITLE
Select asset files recursively

### ISSUE THREAD

**Issue by btk** [btk/pre-require#28]
Currently, our logic is to list all the assets in the top level of given directory path.

We need to list and add the assets to our generated map in a recursive way; 

**Eg;**
```
assets/
  - subasset/
     - subasset1.png
     - subasset2.png
  - asset1.png
  - asset2.png
```

Mapping this like;
```
{
  subasset_subasset1_png: ...,
  subasset_subasset2_png: ...,
  asset1_png: ...,
  asset2_png: ...,
}
```

Seems like a general solution, we should implement it this way. Also we might give user the preference to only list the current top level folder path in the future.

Is there anyone that would like to implement this? Thank you.

**Comment by btk** [comment]
Also I'm second guessing my proposition 
```
assets/
  - subasset/
     - subasset1.png
  - subasset-asset1.png
```
In a situation like this, while mapping 2 file will have the same property name.

We might also think about implementing it in multiple levels of the object.
---

So the eg would be like;
```
assets/
  - subasset/
     - subasset1.png
     - subasset2.png
  - asset1.png
  - asset2.png
```
Mapping this like;
```
{
  subasset: {
     subasset1_png: ...,
     subasset2_png: ...,
  },
  asset1_png: ...,
  asset2_png: ...,
}
```

I'm leaving the choice to person who would like to implement. But keep it in mind implementing it like the second proposition, you might have to revisit and refactor `.format()` and `.search()`.

Thank you.

**Comment by btk** [comment]
Using `recursive-readdir-sync` might be useful for implementing this.

https://www.npmjs.com/package/recursive-readdir-sync

**Comment by hanstf** [comment]
can I try it ?

**Comment by btk** [comment]
@hanstf Yes sure, if you have any questions along the way you can ask it here.

**Comment by hanstf** [comment]
I tried to implement it, you may check in my fork [here](https://github.com/hanstf/pre-require)

**Comment by btk** [comment]
@hanstf that looks good, can you make a pull request so I can compare it with master to analyze more?

**Comment by btk** [comment]
Handled by #30

Thank you so much!
