### ISSUE TITLE
Writing tests for loopDirectory

### ISSUE THREAD

**Issue by btk** [btk/pre-require#32]
Function `loopDirectory()` as implemented by @hanstf might create problems in the future as it does an important task and might have complicated cases.

We should write test for this function especially. Also since it is implemented in an abstract by (thanks to @hanstf) it would be easy to write tests for.

We use jest for tests, If you like to take this on check example tests written by @gatukgl in `./tests/search-file-name.test.js` file.

Creating a js file called `loop-directory.test.js` in tests folder would be good start.

Thank you!

**Comment by FlopiVG** [comment]
#38

**Comment by btk** [comment]
Handled by #38
