### ISSUE TITLE
Development Section in Documentation

### ISSUE THREAD

**Issue by btk** [btk/pre-require#34]
We should update the development section of the documentation (readme.md) 

I started writing about tests in the documentation that thought maybe someone would like to contribute/help since it is Hacktoberfest 🥇 

Basically we need to explain the `package.json` scripts and how to use them while contributing or doing developments.

Thanks!

**Comment by sloansparger** [comment]
I'll take this one 👍

**Comment by btk** [comment]
Handled by #35
