### ISSUE TITLE
Documentation update for new changes

### ISSUE THREAD

**Issue by btk** [btk/pre-require#6]
`pre-require -h`  needs to be added in the documentation. (#5)

Also we have new features in #3 and #4, these new methods (`.search()` and `.format()`) needs to be added to documentation, which we store in our readme file.

Any contribution is welcome.

**Comment by simonstaton** [comment]
Working on this now, Hacktober!

**Comment by btk** [comment]
@simonstaton great! if you could also add examples for each of them it would be nice.

**Comment by btk** [comment]
Thank you!
